### ISSUE TITLE
bengo should have an admin account on https://hollo.socialweb.coop/

### ISSUE THREAD

**Issue by gobengo** [did-coop/activitypub-export#15]
Acceptance Criteria:
* @gobengo and @dmitrizagidulin should have a set of credentials that can log in to the admin dashborad https://hollo.socialweb.coop/

**Comment by gobengo** [comment]
I couldn't quickly figure out how to create this. @0marSalah can you help set this up? you might have to use an admin cli (if there is one?) or edit the database directly. or point me to some docs on how to sign up for an account.

**Comment by 0marSalah** [comment]
i think the first one login is the one who setting to admin,

anyway here is the cred for the admin access

email: admin@admin.admin
password: admin1

**Comment by 0marSalah** [comment]
i am assuming to consider this issue with done!

**Comment by dmitrizagidulin** [comment]
Confirmed that the admin login works.

**Comment by gobengo** [comment]
admin login works. tysm @0marSalah
