### ISSUE TITLE
Add authorization to /accountExport and /accountImport endpoint

### ISSUE THREAD

**Issue by dmitrizagidulin** [did-coop/activitypub-export#3]
Add token-based authorization to the /accountExport endpoint implemented in PR #2.

Follow the same pattern that other protected endpoints use -- see the code suggestion in comment https://github.com/dahlia/hollo/pull/28/files#r1784354543 as a start.

**Comment by gobengo** [comment]
@0marSalah is there a PR for this? It's marked "In Review", but I can't tell how to review it.

**Comment by 0marSalah** [comment]
> @0marSalah is there a PR for this? It's marked "In Review", but I can't tell how to review it.

yeah sure but i have uncomment the part
here is the PR https://github.com/dahlia/hollo/pull/33/
and here is the commit https://github.com/did-coop/hollo/commit/29de95acadc74f05cd5e016d7ad02cc84753bf81

**Comment by 0marSalah** [comment]
Finished with both account-import and account-export branches
without rebasing because the complex git conflict
however both have the authorization using loginRequired authorization middleware

**Comment by 0marSalah** [comment]
the target commit for account-import: https://github.com/did-coop/hollo/commit/c23d2b5ffb888981c8f63893c350a35db953f1e9

for account-export: https://github.com/did-coop/hollo/commit/b3c8af4831ea8fdd91e4c13c497a024bc9fd5f9a

**Comment by 0marSalah** [comment]
Finished and assigned to @dmitrizagidulin to review.

**Comment by dmitrizagidulin** [comment]
Looks good, but fix the space after the comma on the import

**Comment by gobengo** [comment]
What are some next steps on this?

**Comment by 0marSalah** [comment]
oh why this issue still open, its already done from a week ago

**Comment by dmitrizagidulin** [comment]
> oh why this issue still open, its already done from a week ago

Heh, the issue is still open because there was no signal from you that the space after the comma was fixed. In general, I expect a comment from you (+ optionally a reassign to me), when you fix a change request.

Basically, it's open because I didn't know you fixed it :) Closing now though.
