### ISSUE TITLE
Set up a staging Hollo instance

### ISSUE THREAD

**Issue by dmitrizagidulin** [did-coop/activitypub-export#5]
Requirements:

* [x] @gobengo and @dmitrizagidulin provide @0marSalah with a VPS login. `ssh omar@208.113.133.153`
* [x] provide @0marSalah with a domain name to deploy to: `hollo.socialweb.coop`
* [x] @gobengo update DNS records to point to the server `208.113.133.153`.
* [x] Set up Hollo to run from our Hollo fork https://github.com/did-coop/hollo from `main` branch
    * [x] @0marSalah - ensure Hollo runs on port `80`
    * [x] @gobengo - set up Cloudflare to terminate SSL so we can access it via https://hollo.socialweb.coop
    * [x] @0marSalah configure hollo and the server to serve hollo at hollo.socialweb.coop and NOT at staging.hollo.socialweb.coop
    * [x] @0marSalah add brief documentation somewhere with steps to deploy hollo that we can follow if you are unavailable. (i.e. 'ssh to this host, cd to this directory, `git pull && {restartServerCommand}`)
    * [x] https://github.com/did-coop/activitypub-export/issues/12

**Comment by dmitrizagidulin** [comment]
Instructions added to: https://github.com/did-coop/activitypub-export/tree/main/docs/hollo

**Comment by dmitrizagidulin** [comment]
Blocked by: https://github.com/did-coop/activitypub-export/issues/12

**Comment by gobengo** [comment]
I think we can call this done, but I need this as a followup to be able to get value out of the deployment:
https://github.com/did-coop/activitypub-export/issues/15
(Need to be able to log in as admin)

**Comment by dmitrizagidulin** [comment]
Checked that staging is working, marking this as done. (Account creation to follow up in #15).
