### ISSUE TITLE
Add 'Export Your Account' button to Hollo's Settings screen

### ISSUE THREAD

**Issue by dmitrizagidulin** [did-coop/activitypub-export#7]
Now that we have Export working, we need a UI for it.

Task: Find an appropriate place on the Settings screen, add a 'Export Your Account' button.

The button will make a POST to the /accountExport endpoint (using the logged in user's browser cookie), and open the file download dialog.

**Comment by 0marSalah** [comment]
This is finished, assigning to @dmitrizagidulin for closing.

**Comment by dmitrizagidulin** [comment]
Confirmed working, closing.
